In [1]:
!pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
!python -m pip install -U pip
!pip -V
!pip install sklearn pandas

Writing to /root/.config/pip/pip.conf
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already up-to-date: pip in /usr/local/lib/python3.6/dist-packages (20.2.4)
pip 20.2.4 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/


In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.3.1
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
matplotlib 3.3.2
numpy 1.18.5
pandas 1.1.4
sklearn 0.23.2
tensorflow 2.3.1
tensorflow.keras 2.4.0


In [4]:
loaded_keras_model = keras.models.load_model('./graph_def_and_weights/fashion_mnist_model.h5')
loaded_keras_model(np.ones((1,28,28)))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.12158919, 0.08357396, 0.1515581 , 0.01822434, 0.09900576,
        0.00409468, 0.21409407, 0.07169211, 0.21283832, 0.02332938]],
      dtype=float32)>

In [9]:
run_model = tf.function(lambda x: loaded_keras_model(x))
keras_concrete_func = run_model.get_concrete_function(
    tf.TensorSpec(loaded_keras_model.inputs[0].shape, 
                  loaded_keras_model.inputs[0].dtype))

In [11]:
keras_concrete_func(tf.constant(np.ones((1,28,28), dtype=np.float32)))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.12158919, 0.08357396, 0.1515581 , 0.01822434, 0.09900576,
        0.00409468, 0.21409407, 0.07169211, 0.21283832, 0.02332938]],
      dtype=float32)>